volumes:
  mysql:

networks:
  mysql:

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: superheroes
      MYSQL_USER: sa
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: passroot
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      mysql:
        aliases:
          - mysql
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10


  java:
    image: antoine-java:8
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/superheroes
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_URL_PASSWORD: admin
    ports:
      - "8448:8448"
    networks:
      mysql:
        aliases:
          - java
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "localhost:8448"]
      interval: 10s
      timeout: 10s
      retries: 3
 
 
  angular:
    image: antoine-angular:10
    environment:
      - BACKEND_URL_ENV_VAR=http://localhost:8448
    ports:
      - "4200:80"
    networks:
      - mysql
    depends_on:
      java:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "localhost:4200/login"]
      interval: 5s
      timeout: 5s
      retries: 2