name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Java image
      run: docker build . --file Dockerfile --tag antoine-java:$(date +%s)
      
    - name: Build the Angular image
      run: docker build . --file Dockerfile --tag antoine-angular:$(date +%s)
